import re


def clean_mermaid_response(response):

    response = response.replace("```mermaid", "")
    response = response.replace("```", "")
    response = response.replace(";", "")

    # Remove explanations commonly generated by LLMs
    stop_markers = [
        "This Mermaid",
        "Explanation:",
        "Description:",
        "Notes:",
        "The system",
        "- "
    ]

    for marker in stop_markers:
        if marker in response:
            response = response.split(marker)[0]

    response = response.strip()

    # Convert common database nodes
    database_keywords = [
        "Database",
        "DB",
        "Data Store",
        "Storage",
        "Records"
    ]

    lines = response.split("\n")

    updated_lines = []

    for line in lines:

        modified = line

        for keyword in database_keywords:

            # Match:
            # A[Database]
            pattern = rf'(\w+)\[{keyword}\]'

            replacement = rf'\1[({keyword})]'

            modified = re.sub(
                pattern,
                replacement,
                modified
            )

        updated_lines.append(modified)

    # Join cleaned lines
    response = "\n".join(updated_lines)

    # Remove floating invalid lines
    response = remove_invalid_lines(response)

    # Remove duplicate arrows
    response = remove_duplicate_connections(response)

    response = re.sub(
        r'-->\|([^|]+)\|>',
        r'-->|\1|',
        response
    )

    return response


def validate_mermaid_syntax(code):

    """
    Basic Mermaid validation
    """

    import re

    # reject identifiers containing spaces before bracket
    invalid = re.search(
        r'^[A-Za-z]+\s+[A-Za-z]+\[',
        code,
        re.MULTILINE
    )

    if invalid:
        return False

    if not code.startswith("graph"):
        return False

    if len(code.strip()) < 10:
        return False

    return True


def sanitize_input(text):

    """
    Basic input sanitization
    """

    text = re.sub(
        r"<script.*?>.*?</script>",
        "",
        text
    )

    return text.strip()

def is_invalid_description(text):

    text = text.strip()

    # Only numbers
    if text.isdigit():
        return True

    # Too short (single word)
    if len(text.split()) == 1:
        return True

    return False


def is_ambiguous_description(text):

    text = text.strip()

    ambiguous_terms = [
        "hospital system",
        "banking system",
        "inventory system",
        "student portal",
        "ecommerce system",
        "library system"
    ]

    if text.lower() in ambiguous_terms:
        return True

    return False


def remove_invalid_lines(code):

    """
    Remove invalid Mermaid floating text
    """

    cleaned_lines = []

    lines = code.split("\n")

    for line in lines:

        line = line.strip()

        # Skip floating text lines
        if (
            "-->" not in line
            and "[" not in line
            and "(" not in line
            and not line.startswith("graph")
            and line != ""
        ):
            continue

        cleaned_lines.append(line)

    return "\n".join(cleaned_lines)


def remove_duplicate_connections(code):

    """
    Remove duplicate Mermaid connections
    """

    seen = set()

    cleaned_lines = []

    lines = code.split("\n")

    for line in lines:

        stripped = line.strip()

        # Handle connection lines
        if "-->" in stripped:

            if stripped not in seen:

                seen.add(stripped)

                cleaned_lines.append(line)

        else:

            cleaned_lines.append(line)

    return "\n".join(cleaned_lines)